name: 'Deploy to AWS CloudFormation'
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'ap-south-1'
      aws-access-key-id:
        type: string
        description: 'aws-access-key-id'
        required: true
      aws-secret-access-key:
        type: string
        description: 'aws-secret-access-key'  
        required: true
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ github.event.inputs.aws-secret-access-key }}
          aws-region:  ${{ github.event.inputs.aws-region }}
          
      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: AWS-CFT-stack
          template: ec2.yaml
          no-fail-on-empty-changeset: "1"         
