name: 'Deploy to AWS CloudFormation'
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      aws-region:
                  type: choice
                  description: 'region'
                  required: true
                  options:
                    - 'us-east-1'
                    - 'ap-south-1'
      aws-access-key-id:
        type: string
        description: 'aws-access-key-id'
        required: true
      aws-secret-access-key:
        type: string
        description: 'aws-secret-access-key'  
        required: true
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ github.event.inputs.aws-secret-access-key }}
          aws-region:  ${{ github.event.inputs.aws-region }}
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli          
      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation using AWS CLI
        run: |
          aws cloudformation deploy \
            --template-file ec2.yaml \
            --stack-name AWS-CFT-stack \
            --region ${{ github.event.inputs.aws-region }} \
            --no-fail-on-empty-changeset
