name: 'Deploy to AWS CloudFormation'
on: 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      aws-region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'ap-south-1'
      aws-access-key-id:
        type: string
        description: 'aws-access-key-id'
        required: true
      aws-secret-access-key:
        type: string
        description: 'aws-secret-access-key'  
        required: true
jobs: 
  deploy:
    name: Deploy AWS cloud formation   
    runs-on: ubuntu-latest    
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:     
      - name: Checkout code from master branch
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ github.event.inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ github.event.inputs.aws-secret-access-key }}
          aws-region:  ${{ github.event.inputs.aws-region }}
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli    
      - name: Deploy to AWS CloudFormation
        # uses: aws-actions/aws-cloudformation-github-deploy@v1
        # with:
        #   name: AWS-CFT-stack
        #   template: ec2.yaml
        #   no-fail-on-empty-changeset: "1"         
        run: |
          aws cloudformation deploy \
          --template ./ec2.yaml \
          --stack-name AWS-CFT-Stack \         
          --no-fail-on-empty-changeset
